config/routes.rb
Rails.application.routes.draw do
  resources :tutors
  resources :tutors
  resources :tutors

end

app/models/tel_tutor.rb
class TelTutor < ActiveRecord::Base
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
	has_many :TelTutors
	accepts_nested_attributes_for :TelTutors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
    2.times { @tutor.TelTutors.build }
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)
    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: 'Tutor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:tipo_id, :id, :first, :second, :apellido, :lastname, :tipo_tutor, :email, :user_id, :direction, tel_tutor_attributes: [:id,:tipo,:numero])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tel_tutor_helper.rb
module TelTutorHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SACC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tutors/_form.html.erb
<%= form_for(@tutor) do |f| %>
  <% if @tutor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
      <% @tutor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
￼

      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo_id %><br>
    <%= f.text_field :tipo_id %>
  </div>
  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :first %><br>
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :second %><br>
    <%= f.text_field :second %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </div>
  <%= f.fields_for :tel_tutors   do |u| %>
 <div class="field">
   <%= u.label :tipo %><br />
   <%= u.text_field :tipo %>
 </div>
 <div class="field">
   <%= u.label :numero %><br />
   <%= u.text_field :numero %>
 </div>
 <% end %>
  <div class="field">
    <%= f.label :tipo_tutor %><br>
    <%= f.text_field :tipo_tutor %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :direction %><br>
    <%= f.text_field :direction %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tutors/edit.html.erb
<h1>Editing Tutor</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutor %> |
<%= link_to 'Back', tutors_path %>

app/views/tutors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tutors</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Id</th>
      <th>First</th>
      <th>Second</th>
      <th>Apellido</th>
      <th>Lastname</th>
      <th>Tel tutor</th>
      <th>Tipo tutor</th>
      <th>Email</th>
      <th>User</th>
      <th>Direction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutors.each do |tutor| %>
      <tr>
        <td><%= tutor.tipo_id %></td>
        <td><%= tutor.id %></td>
        <td><%= tutor.first %></td>
        <td><%= tutor.second %></td>
        <td><%= tutor.apellido %></td>
        <td><%= tutor.lastname %></td>
        <td><%= tutor.tel_tutor_id %></td>
        <td><%= tutor.tipo_tutor %></td>
        <td><%= tutor.email %></td>
        <td><%= tutor.user_id %></td>
        <td><%= tutor.direction %></td>
        <td><%= link_to 'Show', tutor %></td>
        <td><%= link_to 'Edit', edit_tutor_path(tutor) %></td>
        <td><%= link_to 'Destroy', tutor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutor', new_tutor_path %>

app/views/tutors/new.html.erb
<h1>New Tutor</h1>

<%= render 'form' %>

<%= link_to 'Back', tutors_path %>

app/views/tutors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @tutor.tipo_id %>
</p>

<p>
  <strong>Id:</strong>
  <%= @tutor.id %>
</p>

<p>
  <strong>First:</strong>
  <%= @tutor.first %>
</p>

<p>
  <strong>Second:</strong>
  <%= @tutor.second %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @tutor.apellido %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @tutor.lastname %>
</p>

<p>
  <strong>Tel tutor:</strong>
  <%= @tutor.tel_tutor_id %>
</p>

<p>
  <strong>Tipo tutor:</strong>
  <%= @tutor.tipo_tutor %>
</p>

<p>
  <strong>Email:</strong>
  <%= @tutor.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @tutor.user_id %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @tutor.direction %>
</p>

<%= link_to 'Edit', edit_tutor_path(@tutor) %> |
<%= link_to 'Back', tutors_path %>